version: "3.9"

services:
  db:
    container_name: postgres
    env_file: .env
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    container_name: website
    env_file: .env
    image: registry.digitalocean.com/trah-repo/website
    command: >
      sh -c "python manage.py migrate &&
             python manage.py sync_database &&
             gunicorn --bind :8000 WebsiteDjango.wsgi:application"
    volumes:
      - .:/website
    expose:
      - 8000
    depends_on:
      - db
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"