version: "3.9"

services:
  db:
    env_file: .env
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    env_file: .env
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py sync_database &&
             gunicorn --bind :8000 WebsiteDjango.wsgi:application"
    volumes:
      - .:/website
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: on-failure