# Generated by Django 3.1.3 on 2020-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('url_small', models.URLField(unique=True)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=264)),
                ('orientation', models.CharField(max_length=64)),
            ],
        ),
    ]
